// <auto-generated />
using ZGSTokenBar.PluginSdk;
using ZGSTokenBar.Plugin.SystemMetrics;
using ZGSTokenBar.Plugin.Claude;
using ZGSTokenBar.Plugin.Codex;
using ZGSTokenBar.Plugin.CodexLocal;

namespace ZGSTokenBar.Builtins;

public static class GeneratedBuiltinPluginRegistry
{
    public static IReadOnlyList<IZgsPlugin> Create() =>
    [
        new SystemMetricsPlugin(),
        new ClaudePlugin(),
        new CodexPlugin(),
        new CodexLocalPlugin(),
    ];
}
