<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZGSTokenBar.PluginSdk\ZGSTokenBar.PluginSdk.csproj" />
    <ProjectReference Include="..\Plugins\*\*.csproj" />
  </ItemGroup>
</Project>
