import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import test from 'node:test';

test('built-in plugin registry is generated from strict manifests', () => {
  const result = spawnSync(
    process.execPath,
    ['scripts/generate-builtin-plugin-registry.mjs', '--check'],
    { encoding: 'utf8' });
  assert.equal(result.status, 0, result.stderr || result.stdout);

  const registry = fs.readFileSync(
    'src/ZGSTokenBar.Builtins/GeneratedBuiltinPluginRegistry.g.cs',
    'utf8');
  assert.match(registry, /<auto-generated \/>/);
  assert.doesNotMatch(registry, /Assembly\.Load|GetTypes\(|Activator\.CreateInstance/);

  const manifests = fs.readdirSync('src/Plugins', { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => `src/Plugins/${entry.name}/plugin-manifest.v1.json`)
    .filter(path => fs.existsSync(path));
  assert.equal(manifests.length, 4);
  for (const path of manifests) {
    const manifest = JSON.parse(fs.readFileSync(path, 'utf8'));
    assert.equal(manifest.schemaVersion, 1);
    assert.equal(manifest.runtime, 'builtin');
    assert.match(manifest.id, /^[a-z0-9]+(?:[.-][a-z0-9]+)*$/);
  }
});
