import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';

const read = path => fs.readFileSync(path, 'utf8');
const host = read('src/ZGSTokenBar.Host/ZgsTokenBarHost.cs');
const transport = [
  read('src/ZGSTokenBar.Transport.NamedPipe/ZgsNamedPipeServer.cs'),
  read('src/ZGSTokenBar.Transport.NamedPipe/ZgsNamedPipeClient.cs'),
  read('src/ZGSTokenBar.Transport.NamedPipe/PipeProtocol.cs'),
].join('\n');
const processHost = [
  read('src/ZGSTokenBar.Host/PluginPackageManager.cs'),
  read('src/ZGSTokenBar.Host/ProcessPluginProxy.cs'),
  read('src/ZGSTokenBar.Host/ProcessPluginRuntime.cs'),
].join('\n');
const builtinsProject = read('src/ZGSTokenBar.Builtins/ZGSTokenBar.Builtins.csproj');
const graduationGate = read('scripts/graduation-gate.mjs');

test('plugin host has four generated built-ins and no reflection loading', () => {
  const manifests = fs.readdirSync('src/Plugins', { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => 'src/Plugins/' + entry.name + '/plugin-manifest.v1.json')
    .filter(path => fs.existsSync(path));
  assert.equal(manifests.length, 4);
  const ids = manifests.map(path => JSON.parse(read(path)).id).sort();
  assert.deepEqual(ids, [
    'zgstokenbar.metrics.system',
    'zgstokenbar.provider.claude',
    'zgstokenbar.provider.codex',
    'zgstokenbar.usage.codex-local',
  ]);
  const registry = read('src/ZGSTokenBar.Builtins/GeneratedBuiltinPluginRegistry.g.cs');
  assert.match(registry, /<auto-generated \/>/);
  assert.doesNotMatch(
    registry + '\n' + host,
    /Assembly\.Load|AssemblyLoadContext|GetTypes\(|Activator\.CreateInstance/);
});

test('local API is current-user named pipe with bounded strict frames', () => {
  assert.match(transport, /ZGSTokenBar\.v1\.s\{sessionId\}/);
  assert.match(transport, /PipeOptions\.CurrentUserOnly/);
  assert.match(transport, /MaximumFrameBytes/);
  assert.match(transport, /BinaryPrimitives\.WriteInt32LittleEndian/);
  assert.doesNotMatch(transport, /HttpListener|TcpListener|localhost:/);
});

test('process plugins are package-verified and job-contained', () => {
  assert.match(processHost, /MaximumArchiveBytes = 64L \* 1024 \* 1024/);
  assert.match(processHost, /MaximumExpandedBytes = 128L \* 1024 \* 1024/);
  assert.match(processHost, /MaximumFiles = 256/);
  assert.match(processHost, /FixedTimeEquals/);
  assert.match(processHost, /JobObjectLimitKillOnJobClose/);
  assert.match(processHost, /AssignProcessToJobObject/);
  assert.match(processHost, /host\.credential\.resolve/);
  assert.doesNotMatch(processHost, /UseShellExecute = true/);
  assert.match(processHost, /requestMayHaveBeenWritten/);
  assert.match(processHost, /catch \(OperationCanceledException\) when \(cancellationToken\.IsCancellationRequested\)[\s\S]*?StopProcessAsync/);
  assert.match(processHost, /process\.Kill\(entireProcessTree: true\);[\s\S]*?await process\.WaitForExitAsync\(\)/);
});

test('host uses independent global, config, ui, and plugin data revisions', () => {
  assert.match(host, /_revision/);
  assert.match(host, /_configRevision/);
  assert.match(host, /_uiRevision/);
  assert.match(host, /_dataRevisions/);
  assert.match(host, /state_conflict/);
  assert.match(host, /Channel\.CreateBounded<HostEvent>/);
  assert.match(host, /_dataRevisions\[pluginId\]\+\+;[\s\S]*?InvalidateCursorsLocked\(pluginId\)/);
});

test('plugin extension contract is schema-backed and registry input is open-ended', () => {
  assert.doesNotThrow(() => JSON.parse(read('schemas/plugin-manifest.v1.json')));
  assert.doesNotThrow(() => JSON.parse(read('schemas/local-api.v1.json')));
  assert.match(builtinsProject, /\.\.\\Plugins\\\*\\\*\.csproj/);
  assert.match(graduationGate, /\['dotnet', \[[\s\S]*?'publish'/);
  assert.match(graduationGate, /'acceptance', 'run', '--isolated'/);
  assert.match(graduationGate, /--taskbar-mini-captures/);
});
